Running on nodes: lrdn0903
Arguments passed: 1
/leonardo/home/userexternal/cditulli/thesis
total 28
-rw-r--r-- 1 cditulli interactive    8 Jun 11 17:57 README.md
-rw-r--r-- 1 cditulli interactive  207 Jun 12 11:46 requirements.txt
drwxr-xr-x 2 cditulli interactive 4096 Jun 12 13:03 sout
-rw-r--r-- 1 cditulli interactive  569 Jun 12 13:03 training1.sh
-rw-r--r-- 1 cditulli interactive 9410 Jun 12 11:48 training_clip_msi1.py
Traceback (most recent call last):
  File "/leonardo/prod/spack/5.2/install/0.21/linux-rhel8-icelake/gcc-8.5.0/anaconda3-2023.09-0-zcre7pfofz45c3btxpdk5zvcicdq5evx/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
Traceback (most recent call last):
  File "/leonardo/prod/spack/5.2/install/0.21/linux-rhel8-icelake/gcc-8.5.0/anaconda3-2023.09-0-zcre7pfofz45c3btxpdk5zvcicdq5evx/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/leonardo/home/userexternal/cditulli/thesis/training_clip_msi1.py", line 18, in <module>
    import clip
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/clip/clip.py", line 8, in <module>
    import torch
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "/leonardo/home/userexternal/cditulli/thesis/training_clip_msi1.py", line 29, in <module>
    from sklearn.preprocessing import LabelEncoder
ModuleNotFoundError: No module named 'sklearn'
srun: error: lrdn0903: task 0: Exited with exit code 1
